pub fn print() {
    println!("Pasted CLI Tool (v{})", env!("CARGO_PKG_VERSION"));
    println!("Usage:");
    for line in HELP_LINES {
        println!("{line}");
    }
}

const HELP_LINES: &[&str] = &[
    "  pasted copy <text> [--json] Classify and save content, or pipe stdin",
    "  pasted list [--limit N] [--offset N] [--bin ID|--pinned|--named|--trash] [--json]",
    "  pasted search [query] [--clip TYPE] [--content TYPE] [--format FORMAT] [--source APP] [--ids ID,...] [--trash] [--limit N] [--offset N] [--json]",
    "  pasted import sources [--json] List supported external-history sources",
    "  pasted import <source> [path] --json Import history from another clipboard manager",
    "  pasted diagnostics --json Show installation diagnostics",
    "  pasted insights summary --json Show aggregate clipboard insights",
    "  pasted licenses [--json] Show bundled open-source licenses and notices",
    "  pasted retention [--count N|unlimited] [--days N|forever] [--json]",
    "                   [--trash-count N|unlimited] [--trash-days N|forever]",
    "                   [--log-count N|unlimited] [--log-days N|forever]",
    "                   [--revision-count N|unlimited]",
    "                   [--analysis-count N|unlimited]",
    "  pasted settings list|get|set|reset [arguments] [--dry-run] [--json]",
    "  pasted private-browsing status|enable|disable|fallback [--json]",
    "  pasted app-lock status|enable|change-passphrase|disable|lock|unlock [--stdin] [--json]",
    "  pasted app-lock idle <never|1m|5m|1h|8h> [--stdin] [--json]",
    "  pasted app-lock lock-on-sleep <on|off> [--stdin] [--json]",
    "  pasted app-lock lock-on-restart <on|off> [--stdin] [--json]",
    "  pasted app-lock capture-while-locked <on|off> [--stdin] [--json]",
    "  pasted app-lock system-auth|apple-watch <on|off> [--stdin] [--json]",
    "  pasted app-lock reset-policy [--stdin] [--json]",
    "  pasted app-lock reset --yes [--json]",
    "  pasted recording status|pause|resume [--json] Control the running app",
    "  pasted queue status|start|stop|add|remove|order|paste|paste-all [--json]",
    "  pasted activity list [--limit N|--all] [--json]",
    "  pasted activity export [path] [--format json|csv]",
    "  pasted activity import <path> [--format json|csv] [--json]",
    "  pasted activity clear --yes [--json]",
    "  pasted transfer export|inspect|import <path.json> [--json]",
    "  pasted backup create <path.pastedbackup> [--json]",
    "  pasted backup inspect <path.pastedbackup> [--json]",
    "  pasted backup restore <path.pastedbackup> --yes [--json]",
    "  pasted clip export [path] [--format json|csv]",
    "  pasted clip import <path> [--format json|csv] [--json]",
    "  pasted analyzer run [--text TEXT | --clip ID | --stdin] [--policy POLICY] [--extract] [--json]",
    "  pasted extractor list --json List content Extractors and availability",
    "  pasted extractor create --recipe FILE [options] Create a local recipe",
    "  pasted extractor propose --prompt TEXT Draft a recipe with AI",
    "  pasted extractor preflight <ref> Check local recipe dependencies",
    "  pasted extractor diagnose <ref> Ask AI to revise an unavailable recipe",
    "  pasted extractor history <ref> Review local authoring history",
    "  pasted inspector list --json List content Inspectors",
    "  pasted inspector run [--text TEXT | --clip ID | --stdin] [--apply] [--json]",
    "  pasted suggestion list --json List Suggestion participants",
    "  pasted suggestion run [--text TEXT | --clip ID | --stdin] [--json]",
    "  pasted classifier list --json List editable content classifiers",
    "  pasted type list --json List registered content types",
    "  pasted registry list [--kind KIND] [--json] List shared processing metadata",
    "  pasted registry enable|disable --kind KIND --ref REF",
    "  pasted classifier create|update|delete Manage content classifiers",
    "  pasted classifier rescan --yes --json Reclassify existing text clips",
    "  pasted database location --json Show the active SQLite database",
    "  pasted database protection --json Inspect volume encryption",
    "  pasted database move <folder> --json Move the database (quit Pasted first)",
    "  pasted database default --json Restore the native default location",
    "  pasted ocr status --json Show OCR background-work status",
    "  pasted ocr scan [--clip ID] [--json] Scan eligible images or one clip",
    "  pasted ocr retry|cancel [--json] Retry failures or cancel the running app",
    "  pasted transform list [--json] List saved and manually built Transforms",
    "  pasted transform test --plan-json JSON [--text TEXT|--stdin] [--json]",
    "  pasted transform get|plan|test|create|update|duplicate|delete Manage either Transform authoring form",
    "  pasted transform run <ref> [--text TEXT | --clip ID | --stdin] [--apply]",
    "  pasted operation list|get|create|update|duplicate|delete|run",
    "  pasted connection list|get|detect|create|update|delete|order",
    "  pasted bin list|get|create|update|duplicate|delete [--json]",
    "  pasted bin clips <id> --json List clips in persistent Bin order",
    "  pasted bin order <id> <clip-id>... Persist a complete Bin order",
    "  pasted bin protect|conceal <id> <on|off> [--json]",
    "  pasted clip get|name <id> [options] [--json]",
    "  pasted clip labels list|add|remove|reset <id> [label] [--yes] [--json]",
    "  pasted clip copy|paste <id> [--json] Use the running app and system clipboard",
    "  pasted clip hotkey <id> <hotkey|none> [--json]",
    "  pasted clip pin|unpin <id>... [--json]",
    "  pasted clip order-pinned <id>... [--json]",
    "  pasted clip protect|unprotect|conceal|reveal <id>... [--json]",
    "  pasted clip trash|restore <id>... [--json]",
    "  pasted clip restore-all [--json] Restore every clip from Trash",
    "  pasted clip note <id> [options] [--json]",
    "  pasted clip versions <id> [--limit N] [--offset N] [--json]",
    "  pasted clip restore-version <id> <version-id> [--json]",
    "  pasted clip delete-version <id> <version-id> --yes [--json]",
    "  pasted clip provenance <id> [--json]",
    "  pasted clip purge <id>... --yes | empty-trash --yes",
    "  pasted clip assign <bin-id|none> <id>... [--json] Add to a Bin, or clear all manual Bins",
    "  pasted clip remove-bin <bin-id> <id>... [--json]",
    "  pasted clear             Clear unpinned clipboard history",
    "  pasted reset --yes [--json] Reset all Pasted data and preferences",
];
