use super::*;

pub const EXTRACTOR_PRESETS: &[ExtractorPreset] = &[
    ExtractorPreset {
        stable_ref: APPLE_VISION_OCR_REF,
        name: "Apple Vision OCR",
        description: "Extracts searchable text from images locally with Apple Vision.",
        engine: RECIPE_ENGINE,
        executable_path: None,
        model_path: None,
        input_contract: RepresentationKind::ImageBytes.stable_name(),
        output_contract: RepresentationKind::SearchableText.stable_name(),
        priority: 10,
        revision: 5,
    },
    ExtractorPreset {
        stable_ref: APPLE_VISION_LABELS_REF,
        name: "Apple Vision Labels",
        description: "Finds searchable subjects and objects in images locally with Apple Vision.",
        engine: RECIPE_ENGINE,
        executable_path: None,
        model_path: None,
        input_contract: RepresentationKind::ImageBytes.stable_name(),
        output_contract: RepresentationKind::SearchableText.stable_name(),
        priority: 15,
        revision: 4,
    },
    ExtractorPreset {
        stable_ref: LLAMA_CPP_LABELS_REF,
        name: "llama.cpp Labels",
        description: "Finds searchable subjects and objects in images locally with llama.cpp.",
        engine: RECIPE_ENGINE,
        executable_path: None,
        model_path: None,
        input_contract: RepresentationKind::ImageBytes.stable_name(),
        output_contract: RepresentationKind::SearchableText.stable_name(),
        priority: 20,
        revision: 2,
    },
    ExtractorPreset {
        stable_ref: TESSERACT_OCR_REF,
        name: "Tesseract OCR",
        description: "Extracts searchable text from images locally with Tesseract.",
        engine: RECIPE_ENGINE,
        executable_path: None,
        model_path: None,
        input_contract: RepresentationKind::ImageBytes.stable_name(),
        output_contract: RepresentationKind::SearchableText.stable_name(),
        priority: 30,
        revision: 4,
    },
    ExtractorPreset {
        stable_ref: WHISPER_TRANSCRIPTION_REF,
        name: "Whisper Transcription",
        description: "Extracts searchable text from local audio files with whisper.cpp.",
        engine: RECIPE_ENGINE,
        executable_path: None,
        model_path: None,
        input_contract: RepresentationKind::FileReferences.stable_name(),
        output_contract: RepresentationKind::SearchableText.stable_name(),
        priority: 40,
        revision: 4,
    },
];
